#!/bin/bash
genesis simInputComp.g 2HzV1 soma
genesis simInputComp.g 2HzV1 at4a 
genesis simInputComp.g 2HzV1 at2b
genesis simInputComp.g 2HzV1 as4b
genesis simInputComp.g 8HzV1 soma
genesis simInputComp.g 8HzV1 at4a 
genesis simInputComp.g 8HzV1 at2b
genesis simInputComp.g 8HzV1 as4b
genesis simInputComp.g 16HzV1 soma
genesis simInputComp.g 16HzV1 at4a 
genesis simInputComp.g 16HzV1 at2b
genesis simInputComp.g 16HzV1 as4b
genesis simInputComp.g 53HzV1 soma
genesis simInputComp.g 53HzV1 at4a 
genesis simInputComp.g 53HzV1 at2b
genesis simInputComp.g 53HzV1 as4b
genesis simInputComp.g 2HzV2 soma
genesis simInputComp.g 2HzV2 at4a 
genesis simInputComp.g 2HzV2 at2b
genesis simInputComp.g 2HzV2 as4b
genesis simInputComp.g 8HzV2 soma
genesis simInputComp.g 8HzV2 at4a 
genesis simInputComp.g 8HzV2 at2b
genesis simInputComp.g 8HzV2 as4b
genesis simInputComp.g 16HzV2 soma
genesis simInputComp.g 16HzV2 at4a 
genesis simInputComp.g 16HzV2 at2b
genesis simInputComp.g 16HzV2 as4b
genesis simInputComp.g 53HzV2 soma
genesis simInputComp.g 53HzV2 at4a 
genesis simInputComp.g 53HzV2 at2b
genesis simInputComp.g 53HzV2 as4b
genesis simInputComp.g 2HzV3 soma
genesis simInputComp.g 2HzV3 at4a 
genesis simInputComp.g 2HzV3 at2b
genesis simInputComp.g 2HzV3 as4b
genesis simInputComp.g 8HzV3 soma
genesis simInputComp.g 8HzV3 at4a 
genesis simInputComp.g 8HzV3 at2b
genesis simInputComp.g 8HzV3 as4b
genesis simInputComp.g 16HzV3 soma
genesis simInputComp.g 16HzV3 at4a 
genesis simInputComp.g 16HzV3 at2b
genesis simInputComp.g 16HzV3 as4b
genesis simInputComp.g 53HzV3 soma
genesis simInputComp.g 53HzV3 at4a 
genesis simInputComp.g 53HzV3 at2b
genesis simInputComp.g 53HzV3 as4b
genesis simInputComp.g 2HzV4 soma
genesis simInputComp.g 2HzV4 at4a 
genesis simInputComp.g 2HzV4 at2b
genesis simInputComp.g 2HzV4 as4b
genesis simInputComp.g 8HzV4 soma
genesis simInputComp.g 8HzV4 at4a 
genesis simInputComp.g 8HzV4 at2b
genesis simInputComp.g 8HzV4 as4b
genesis simInputComp.g 16HzV4 soma
genesis simInputComp.g 16HzV4 at4a 
genesis simInputComp.g 16HzV4 at2b
genesis simInputComp.g 16HzV4 as4b
genesis simInputComp.g 53HzV4 soma
genesis simInputComp.g 53HzV4 at4a 
genesis simInputComp.g 53HzV4 at2b
genesis simInputComp.g 53HzV4 as4b
